понедельник, 16 июня 2014 г. 20:16:16 (MSK)
Traceback (most recent call last):
  File "/Users/vladsaveliev/vagrant/reporting_suite/varqc_summary.py", line 56, in <module>
    main(sys.argv[1:])
  File "/Users/vladsaveliev/vagrant/reporting_suite/varqc_summary.py", line 32, in main
    with open(samples_fpath, 'r') as f:
IOError: [Errno 2] No such file or directory: 'sample1,sampl+e2'
понедельник, 16 июня 2014 г. 20:16:16 (MSK)
